// ==========================================
// VocalMap Localization & Translation Manager
// ==========================================

const LANG_DICTIONARY = {
    zh: {
        // Top Navigation
        '#tabBtnFree': '<i data-lucide="activity" class="lucide-icon"></i> 实时监视',
        '#tabBtnPro': '<i data-lucide="crown" class="lucide-icon"></i> Pro 核心功能',
        '#btnSettings': '<i data-lucide="sliders" class="lucide-icon"></i> 引擎参数',
        '#btnHelp': '<i data-lucide="help-circle" class="lucide-icon"></i>',
        '#startBtn': '<i data-lucide="zap" class="lucide-icon"></i> 启动引擎',
        '#btnCheckUpdate': '检查更新',
        '#btnInstallUpdate': '重启安装',
        
        // Workspace Free
        '#freeWorkspace .dashboard-title': '声学监视特征数据',
        '#btnToggleRecord': '<i data-lucide="circle-dot" class="lucide-icon"></i> 开始监视录制',
        '#btnPlayPause': '<i data-lucide="play" class="lucide-icon"></i> 播放',
        '#btnClosePlayback': '<i data-lucide="x" class="lucide-icon"></i> 关闭',
        '#btnExportRecord': '<i data-lucide="download" class="lucide-icon"></i> 导出',
        '#btnImportRecord': '<i data-lucide="folder-open" class="lucide-icon"></i> 导入',
        '#playbackTime': '0.0s / 0.0s',
        '#recordStatusText': '录制中... 0.0s',
        
        // Free Gauge Titles
        '#titlePitch': '音高 (Pitch)',
        '#titleDev': '音准 (Cents)',
        '#titleLoud': '响度 (Loud)',
        '#titleBright': '机能 (H1/H2)',
        '#titlePure': '纯净 (HNR)',
        '#titleStab': '稳定 (Jitter)',
        '#trainTitlePitch': '音高 (Pitch)',
        '#trainTitleDev': '音准 (Cents)',
        '#trainTitleLoud': '响度 (Loud)',
        '#trainTitleBright': '机能 (H1/H2)',
        '#trainTitlePure': '纯净 (HNR)',
        '#trainTitleStab': '稳定 (Jitter)',
        '#descPitch, #trainDescPitch': '等待发声...',
        '#descDev, #trainDescDev': '等待发声...',
        '#descLoud, #trainDescLoud': '正常',
        '#descBright, #trainDescBright': '等待发声...',
        '#descPure, #trainDescPure': '等待发声...',
        '#descStab, #trainDescStab': '等待发声...',
        
        // Workspace Pro Tabs
        '#btnSubTabSing': '<i data-lucide="mic" class="lucide-icon"></i> 歌声检测',
        '#btnSubTabTrain': '<i data-lucide="target" class="lucide-icon"></i> 关卡训练营',
        '#btnSubTabSep': '<i data-lucide="split" class="lucide-icon"></i> 音轨分离',
        
        // Workspace Pro - Sing/Diagnosis
        '#proStateIdle h2': '歌声全息诊断系统',
        '#proStateIdle p': '点击下方按钮开始录制人声进行诊断，或直接导入本地音频文件进行毫秒级提取，获取五维声学诊断报告。',
        '#btnStartRecord': '<i data-lucide="mic" class="lucide-icon"></i> 麦克风实时检测',
        '#btnImportAudioDetect': '<i data-lucide="upload" class="lucide-icon"></i> 导入音频检测',
        '#proStateRecording h2': '正在检测歌声... <span id="recordTimer" style="font-family: \'JetBrains Mono\', monospace; color: white;">0.0s</span>',
        '#proStateRecording p': '请对着麦克风歌唱，建议保持稳定的长音或唱一段完整的旋律。',
        '#btnStopRecord': '<i data-lucide="square" class="lucide-icon"></i> 停止检测并分析',
        '#proStateReport h2': '<i data-lucide="bar-chart-2" class="lucide-icon"></i> 歌声诊断报告',
        '#btnExportImage': '<i data-lucide="camera" class="lucide-icon"></i> 导出报告长图',
        '#btnExportVmap': '<i data-lucide="save" class="lucide-icon"></i> 存为回放项目',
        '#btnResetRecord': '<i data-lucide="refresh-cw" class="lucide-icon"></i> 重新开始检测',
        
        // Workspace Pro - Separation
        '#sepDeviceBar span:first-child': '<i data-lucide="cpu" class="lucide-icon" style="margin-right: 4px;"></i> 运行设备:',
        '#btnGPU': '<i data-lucide="zap" class="lucide-icon"></i> GPU 加速',
        '#btnCPU': '<i data-lucide="cpu" class="lucide-icon"></i> CPU 兼容',
        '#sepDeviceBar span:last-child': '(首选 GPU，显存需 >6GB)',
        '#sepPanelsContainer > div:first-child span': '6-Stem 乐器分离',
        '#sepPanelsContainer > div:first-child p': 'Logic-RoFormer 专业级乐器与声部离线分离',
        '#sepInstUploadZone p:nth-child(2)': '选择本地音频文件',
        '#btnStartSepInst': '<i data-lucide="zap" class="lucide-icon"></i> 启动乐器分离',
        '#sepInstProcessing p:nth-child(2)': '乐器声部离线分离中...',
        '#sepInstProcessing p:nth-child(3)': '算法正在进行高速傅里叶变换，请耐心等待...',
        '#sepInstResults h3': '<i data-lucide="check" class="lucide-icon"></i> 乐器分离完成',
        '#btnResetSepInst': '重置分离控制台',
        '#sepPanelsContainer > div:last-child span': '主唱与和声分离',
        '#sepPanelsContainer > div:last-child p': 'BS-RoFormer 高维卷积神经网络人声提取',
        '#sepVocUploadZone p:nth-child(2)': '选择本地音频文件',
        '#btnStartSepVoc': '<i data-lucide="mic" class="lucide-icon"></i> 启动人声分离',
        '#sepVocProcessing p:nth-child(2)': '主唱/背景和声离线分离中...',
        '#sepVocProcessing p:nth-child(3)': '深度学习推理进行中，请耐心等待...',
        '#sepVocResults h3': '<i data-lucide="check" class="lucide-icon"></i> 分离完成',
        '#btnResetSepVoc': '重置分离控制台',
        
        // Workspace Pro - Training
        '#trainingRangeView h2': '<i data-lucide="target" style="color: var(--primary-cyan); margin-right: 8px;"></i>声域自适应关卡训练营 (Pro)',
        '#trainingRangeView h3': '1. 请选择您的所属声部与声域 (Vocal Range)',
        '.range-card[data-range="soprano"] div:first-child': '女高音 (Soprano)',
        '.range-card[data-range="mezzo"] div:first-child': '女中音 (Mezzo)',
        '.range-card[data-range="alto"] div:first-child': '女低音 (Alto)',
        '.range-card[data-range="tenor"] div:first-child': '男高音 (Tenor)',
        '.range-card[data-range="baritone"] div:first-child': '男中音 (Baritone)',
        '.range-card[data-range="bass"] div:first-child': '男低音 (Bass)',
        '.range-card[data-range="custom"] div:first-child': '自定义音域 (Custom)',
        '.range-card[data-range="custom"] #customRangeDisplayText': '点击设置音区',
        '#customRangeConfigPanel h4': '<i data-lucide="sliders" style="display: inline-block; width: 16px; height: 16px; vertical-align: middle; margin-right: 6px; margin-top: -2px;"></i>设置您的极限音域',
        '#customRangeConfigPanel label:first-child': '最低音 (胸声底线)',
        '#customRangeConfigPanel label:nth-child(2)': '最高音 (胸声极限)',
        '#customRangeConfigPanel button': '确认 <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-arrow-right"><path d="M5 12h14"/><path d="m12 5 7 7-7 7"/></svg>',
        '#trainingLevelView h2': '<i data-lucide="target" style="color: var(--primary-cyan); margin-right: 8px;"></i>选择关卡开始训练',
        '#trainingLevelView button': '<i data-lucide="chevron-left" class="lucide-icon"></i> 返回声部选择: <span id="displaySelectedRange" style="color: var(--primary-cyan); font-weight: bold;">--</span>',
        '.level-card[data-level="1"] .level-title': '关卡 1: 热身激活',
        '.level-card[data-level="1"] .level-subtitle': '自然大调音阶随机上下行慢速热身',
        '.level-card[data-level="2"] .level-title': '关卡 2: 气息稳定',
        '.level-card[data-level="2"] .level-subtitle': '超长音高保持，考核声带长程控制能力',
        '.level-card[data-level="3"] .level-title': '关卡 3: 转音练习',
        '.level-card[data-level="3"] .level-subtitle': '密集的五声音阶随机跑动，考验声带瞬态灵敏度',
        '.level-card[data-level="4"] .level-title': '关卡 4: 音准精修',
        '.level-card[data-level="4"] .level-subtitle': '大跨度随机音程跳跃，击碎起音不准的痛点',
        '.level-card[data-level="5"] .level-title': '关卡 5: 三类共鸣',
        '.level-card[data-level="5"] .level-subtitle': '声部音域精准映射，定向考核胸声、混声与头声共鸣',
        '.level-card[data-level="6"] .level-title': '关卡 6: 综合挑战',
        '.level-card[data-level="6"] .level-subtitle': '1分钟全维声学音高随机挑战',
        '#trainingActiveLevelName': '当前正在训练: 关卡 1 热身激活',
        '#trainingSessionView .score-container span:first-child': '当前得分:',
        '#trainingSessionView .btn-danger': '<i data-lucide="log-out" class="lucide-icon" style="width: 14px; height: 14px;"></i> 退出训练舱',
        '#trainingInstructionText': '准备开始',
        
        // Premium Overlay
        '#premiumOverlay h1': 'VocalMap <span style="background: var(--gradient-accent); -webkit-background-clip: text; color: transparent;">Pro</span> 专业特权激活',
        '#premiumOverlay p:first-of-type': '激活后即可解锁全息声学诊断、雷达图报告导出及音轨分离等高级功能。',
        '#premiumOverlay div:nth-of-type(1) span': '本机硬件设备指纹: ',
        '#premiumOverlay div:nth-of-type(2) span': 'CDK 激活码:',
        '#btnActivateCDK': '<i data-lucide="key" class="lucide-icon"></i> 一键激活 Pro 特权',
        '#btnBuyMonthly': '<i data-lucide="calendar" class="lucide-icon"></i> 购买月度通行证 <span style="font-size: 24px; font-weight: 800; margin-left: 8px;">￥ 19.9</span>',
        '#btnBuyLifetime': '<i data-lucide="infinity" class="lucide-icon"></i> 购买永久买断版 <span style="font-size: 24px; font-weight: 800; margin-left: 8px;">￥ 59.9</span>',
        '#btnRefreshStatus': '<i data-lucide="refresh-cw" class="lucide-icon"></i> 重新验证激活状态',
        
        // Training Result Modal
        '#trainingResultModal h2': '训练挑战结束',
        '#trainingResultModal p': '本次声部自适应训练成绩反馈如下',
        '#trainingResultModal .btn-cyan': '确定并退出训练舱',
        
        // Help Modal Header
        '#helpModal h2': 'VocalMap 使用帮助与诊断手册',
        '#helpTabBtn_intro': '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" data-lucide="zap" aria-hidden="true" class="lucide lucide-zap lucide-icon"><path d="M4 14a1 1 0 0 1-.78-1.63l9.9-10.2a.5.5 0 0 1 .86.46l-1.92 6.02A1 1 0 0 0 13 10h7a1 1 0 0 1 .78 1.63l-9.9 10.2a.5.5 0 0 1-.86-.46l1.92-6.02A1 1 0 0 0 11 14z"></path></svg> 快速入门',
        '#helpTabBtn_pro': '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" data-lucide="crown" aria-hidden="true" class="lucide lucide-crown lucide-icon"><path d="M11.562 3.266a.5.5 0 0 1 .876 0L15.39 8.87a1 1 0 0 0 1.516.294L21.183 5.5a.5.5 0 0 1 .798.519l-2.834 10.246a1 1 0 0 1-.956.734H5.81a1 1 0 0 1-.957-.734L2.02 6.02a.5.5 0 0 1 .798-.519l4.276 3.664a1 1 0 0 0 1.516-.294z"></path><path d="M5 21h14"></path></svg> Pro 核心功能',
        '#helpTabBtn_advanced': '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" data-lucide="sliders" aria-hidden="true" class="lucide lucide-sliders lucide-icon"><path d="M10 8h4"></path><path d="M12 21v-9"></path><path d="M12 8V3"></path><path d="M17 16h4"></path><path d="M19 12V3"></path><path d="M19 21v-5"></path><path d="M3 14h4"></path><path d="M5 10V3"></path><path d="M5 21v-7"></path></svg> 算法参数微调',
        '#helpTabBtn_faq': '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" data-lucide="message-square" aria-hidden="true" class="lucide lucide-message-square lucide-icon"><path d="M22 17a2 2 0 0 1-2 2H6.828a2 2 0 0 0-1.414.586l-2.202 2.202A.71.71 0 0 1 2 21.286V5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2z"></path></svg> 高阶技巧与FAQ',
        '#helpTabBtn_about': '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" data-lucide="info" aria-hidden="true" class="lucide lucide-info lucide-icon"><circle cx="12" cy="12" r="10"></circle><path d="M12 16v-4"></path><path d="M12 8h.01"></path></svg> 版本与反馈',
        '#helpModal .help-modal-footer button': '已知晓，开始体验',

        '#help_intro_title': '实时声学监视与特征解析',
        '#help_intro_desc': 'VocalMap 拥有毫秒级的实时声学诊断引擎。在“实时监视”模块，您可以实时观察嗓音的动态表现，生成声学指纹数据。',
        '#help_intro_c1_title': '1. 启动监视与录制',
        '#help_intro_c1_desc': '首先点击导航栏右侧的<b>“启动引擎”</b>，然后对着麦克风发声或歌唱。系统将以极低延迟绘制出音高轨迹曲线。',
        '#help_intro_c2_title': '2. 零延迟项目回放',
        '#help_intro_c2_desc': '点击左下角的<b>“开始监视录制”</b>，对着麦克风发声或歌唱，点击<b>“结束监视录制”</b>后，回放控制条将自动显现。您可点击“播放/暂停”复盘刚刚的演唱，拖拽进度条能随意跳跃。回放时视窗会自动聚焦，鼠标中心纵向白线锁定当前播放时间点的精确 MIDI 音高与分数值。',
        '#help_intro_c3_title': '3. 导入与导出 (.vmap)',
        '#help_intro_c3_desc': '录制结束后，点击右下角的<b>“导出”</b>按钮，可将完整的录音波形和声学曲线打包保存为专属的 `.vmap` 项目文件。日后点击<b>“导入”</b>即可完美复原历史监视会话进行二次复盘。',
        '#help_intro_title2': '实时声学指纹指标说明',
        '#help_intro_badge1': '音高 (Pitch)',
        '#help_intro_badge1_desc': '使用基于 YIN 音高追踪的变体算法，毫秒级捕捉基频并转化为十二平均律 MIDI 唱名。',
        '#help_intro_badge2': '机能 (H1/H2)',
        '#help_intro_badge2_desc': '分析基音（H1）与第一泛音（H2）的相对能量比，评估声带闭合程度与共鸣度。',
        '#help_intro_badge3': '纯净 (HNR)',
        '#help_intro_badge3_desc': '谐噪比评估。音质越纯净值越高（如 20dB 以上），沙哑或漏气声会导致数值下降。',
        '#help_intro_badge4': '稳定 (Jitter)',
        '#help_intro_badge4_desc': '微观音高抖动率。评估声带振动的周期稳定性，普通演唱应控制在 1.5% 以下。',

        '#help_pro_title': 'Pro 核心功能操作指南',
        '#help_pro_desc': '专业版解锁了全息诊断雷达大脑与 SOTA 级别的 RoFormer 音轨分离引擎，是声乐教学和混音后期制作的终极利器。',
        '#help_pro_c1_title': '1. 专业歌声全息诊断与雷达图',
        '#help_pro_c1_desc': '在“Pro 核心功能 -&gt; 歌声检测”子页面，您可以点击<b>“麦克风实时检测”</b>开始录制长乐句，或直接<b>“导入音频检测”</b>（算法会在后台执行极速毫秒级离线全量提取）。分析完成后，系统将呈现一个<b>五维声学雷达图</b>，包含音准命中率、机能共鸣、纯净度、稳定度和颤音评分的精确统计。',
        '#help_pro_c2_title': '2. 导出高清长图报告',
        '#help_pro_c2_desc': '诊断报告出炉后，您可以点击<b>“导出报告长图”</b>。系统将自动生成无损、超清的长截图 PNG 报告，完美保存雷达图 and 各项量化分数，方便分享给社交平台或进行教学存档。',
        '#help_pro_c3_title': '3. 录音棚级高精度音轨分离',
        '#help_pro_c3_desc': '针对音频提取 and 伴奏剥离，提供两种业界顶尖的深度学习神经网络模型：',
        '#help_pro_c3_li1': '<b>6-Stem 乐器分离 (Logic-RoFormer)</b>：将音频剥离为伴奏、人声、鼓、贝斯、钢琴、吉他等独立声部。',
        '#help_pro_c3_li2': '<b>干声与和声分离 (BS-RoFormer Karaoke)</b>：将音频剔除原唱，提取极致纯净的主唱干声与背景和声。',
        '#help_pro_c3_desc_extra': '在分离面板顶部可快捷切换“GPU 加速”（显存需 &gt;6GB，推理极速）或“CPU 兼容”模式。',
        '#help_pro_c4_title': '4. 靶向训练营动态运镜',
        '#help_pro_c4_desc': '在“Pro 核心功能 -&gt; 关卡训练营”中，您可以先选择自己的所属声部（如男高音、女低音等），系统将自动为您规划最适合的练习音域。<br><br><b>六大进阶关卡包含：</b><br>1. <b>稳定音高</b>：练习在基础发声中的音准保持。<br>2. <b>连音爬音</b>：练习气息支撑下平滑的音阶过渡。<br>3. <b>布鲁斯转音</b>：训练声带灵活性和快速反应。<br>4. <b>颤音控制</b>：练习喉头放松，保持声音的波动美感。<br>5. <b>真假声断音</b>：训练声带边缘振动与快速闭合。<br>6. <b>综合大考</b>：结合以上所有技巧的综合实战训练。<br><br><b>智能视野跟随：</b>训练期间，您无需任何手动操作。在遇到跨度极大的高低音时，画面会自动提前平滑移动，为您提供最清晰的练习视野。',

        '#help_adv_title': '声学引擎底层参数调节说明',
        '#help_adv_desc': '点击导航栏右上角的<b>“引擎调节”</b>可唤起参数配置面板。针对不同的使用环境 and 录音硬件，微调这三个核心阈值能将识别精度发挥到极致：',
        '#help_adv_c1_title': '响度激活门限 (Loudness Gate)',
        '#help_adv_c1_desc': '<b>推荐基准值: 8</b><br>这是触发系统开始捕捉音高的最低音量门限。如果您处于喧闹的教学班级或房间，或者您的麦克风有强烈的交流电嗡嗡声底噪，建议将该值调高（如 12 至 15），从而有效防止环境音导致仪表盘无辜跳动。',
        '#help_adv_c2_title': '发声纯净度门限 (Clarity Threshold)',
        '#help_adv_c2_desc': '<b>推荐基准值: 0.65</b><br>用于控制系统对“漏气发声/气泡音/呼吸声”的捕获灵敏度。如果您想做气声哼唱、弱音或边缘振动（Vocal Fry）的精细测量，可将此值调低（如 0.4 至 0.5）。若是在普通的现场歌唱检测中，建议维持 0.65 或更高，以过滤换气时的气流声干扰。',
        '#help_adv_c3_title': '底噪极速追踪门限 (Noise Tracking)',
        '#help_adv_c3_desc': '<b>推荐基准值: 20</b><br>控制降噪追踪器的敏感深度。当外界噪音或音频背景声的响度降到该临界点以下时，底层降噪追踪器会判定此时“歌手已停止发声”，在数毫秒内将信号强制静音归零。这能杜绝音高曲线上出现莫名的“尾音拖尾”杂点。',

        '#help_faq_title': '声乐教学与分析高阶独门技巧',
        '#help_faq_t1_strong_txt': '终极教学秘籍：如何完美测量一首现成歌曲的歌手精确音高？',
        '#help_faq_t1_desc1': '现成发行的流行乐曲中由于带有宏大的管弦乐、吉他或鼓声伴奏，如果直接导入声学检测，乐器的基频会极大干扰 YIN 追踪器，导致音高轨迹频繁乱跳或根本无法锁定。',
        '#help_faq_t1_bold_txt': '完美破解流线',
        '#help_faq_t1_desc2': '先将音轨导入到 <b>Pro 核心功能 -&gt; 音轨分离</b>，启动<b>“干声与和声分离”</b>，提取出纯人声（Vocals Stem）并保存到本地。随后，将该人声 WAV 文件导入 <b>歌声检测 -&gt; 导入音频检测 -&gt; 存为回放项目 -&gt; 实时监视 -&gt; 导入</b>。这样，系统测得的将是绝无干扰、极其平滑且 100% 对应歌手本人的真实物理音高与颤音轨迹！',
        '#help_faq_t2_strong_txt': '靶向得分换算机制',
        '#help_faq_t2_desc': '训练营的得分不仅考量您的绝对音准，还引入了<b>瞬态响应时间</b>与<b>维持稳定度</b>的双重动态扣分换算。当您的音高完全击中靶向方块中心且持续稳定，将获得满分；若音高游离于边缘或发生明显抖动（Jitter过高），系统将动态扣减分值。高频度练习此机制能显著提升声带的闭合控制力。',
        '#help_faq_t3_strong_txt': 'Soprano/Baritone 各声部物理共鸣基准表',
        '#help_faq_t3_desc': '每个声部在进行跨越换声区（Passaggio）的训练时，其物理共鸣焦点是不同的。以 <b>女高音 (Soprano)</b> 为例，核心换声点通常在 F#5 附近，胸声主要集中在 C4-F4，进入头声的靶心多为 C5 以上；而 <b>男中音 (Baritone)</b> 的换声点则落在 Eb4-E4，其低频胸区（G2-C3）是巩固下盘机能的关键。您可以在“三类共鸣”等关卡中体验该基准表的靶向映射。',
        '#help_faq_qa_heading': '常见问答 Q&amp;A',
        '#help_faq_q1_title': 'Q: 运行音轨分离时，首次启动或推理需要多长时间？',
        '#help_faq_q1_desc': 'A: 所有的核心 AI 模型权重文件和便携式推理库<b>已由系统内置的动态下载管理器在首次启动时拉取并校验完毕</b>。当您第一次在分离面板中启动推理时，Python 引擎需要一些时间将大模型从磁盘加载到显存/内存中，请耐心等待；加载完成后，后续的分离运算将是完全本地化、极速无感的高速离线推理。',
        '#help_faq_q2_title': 'Q: 音轨分离提取后，为什么保存或下载总是卡顿？',
        '#help_faq_q2_desc': 'A: 之前版本的 Tauri JS-to-Rust 二进制桥接在传输大体积无损 WAV 文件时会导致 UI 短暂假死。VocalMap v2.8.2引入了<b>本地 FastAPI 零拷贝（Zero-Copy）直写技术</b>，剥离出来的音轨由 Python 引擎直接以物理速度写入目标磁盘，彻底避免了内存占用与界面响应迟钝。先前版本用户请先行更新至v2.8.2以上版本即可解决。',
        '#help_faq_q3_title': 'Q: 为什么无法显示软件版本号，或界面有卡死感觉？',
        '#help_faq_q3_desc': 'A: 这通常代表本地 Python 诊断引擎被安全软件（如 360 或 Windows Defender）拦截、或者 WebSocket 通信接口（5050 端口）被其他本地代理软件占用。请尝试将软件加入杀毒白名单，并确保没有其他应用程序占用 5050 端口。',

        '#help_about_title': '版本、授权激活与问题反馈',
        '#help_about_c1_title': 'VocalMap Pro 专业特权激活',
        '#help_about_c1_desc': '系统为保护原创底层算法，对高级全息诊断和音轨分离实行设备绑定授权锁。您可以在 Pro 激活界面查看本机的<b>“硬件指纹”</b>，在官方渠道购买月度通行证或永久买断版 CDK，粘贴至输入框一键激活，云端将秒级下发本地离线许可证书。',
        '#help_about_c2_title': 'OTA 极速静默升级',
        '#help_about_c2_desc': '在顶部导航栏中，您可以一键<b>“检查更新”</b>。升级程序已接入高速分发网，发现新版本后会自动在后台异步流式下载，下载完成后只需点击<b>“重启安装”</b>即可无感替换主程序，保证您的核心 AI 模型与声学算法始终处于业界最前沿！',
        '#help_about_c3_title': '遇到系统故障？一键 GitHub 反馈',
        '#help_about_c3_desc': '声卡驱动不兼容、神经网络崩溃、或者是对声学指纹有更好的改进建议？您可以随时点击下方按钮前往我们的官方开源社区提交 Issue，开发团队将在第一时间响应！',
        '#help_about_btn': '<i data-lucide="github" class="lucide-icon"></i> 前往 GitHub 提交反馈与故障日志',
        
        // Settings Modal
        '#settingsModal h2': '<i data-lucide="sliders" class="lucide-icon"></i> 声学引擎高级参数设置',
        '#labelMicrophone': '麦克风输入设备 (Microphone)',
        '#descMicrophone': '选择您用于录音 and 演唱的麦克风硬件设备。更改后建议重新启动声学引擎以完成连接桥接。',
        '#labelLoudnessGate': '响度激活门限 (Loudness Gate)',
        '#descLoudnessGate': '触发系统开始捕捉音高的最低音量门限。若外界噪音较大，可将该值调高（如 15-20）以杜绝环境音导致的偶发跳动。<br><b>推荐基准值: 12</b>',
        '#labelClarityThreshold': '发声纯净度门限 (Clarity Threshold)',
        '#descClarityThreshold': '控制系统对“气流漏气/气泡音/弱发声”的捕获灵敏度。若做弱边缘振动或哼鸣练习，可将此值调低（如 0.4-0.5）。<br><b>推荐基准值: 0.65</b>',
        '#labelNoiseTracking': '底噪降噪追踪门限 (Noise Tracking)',
        '#descNoiseTracking': '降噪门限追踪深度。当输入音频低于该阈值时判定为无声状态并强制归零，防止音高曲线上出现“尾音拖尾”杂点。<br><b>推荐基准值: 20</b>',
        '#labelPianoVolume': '钢琴示范音量 (Piano Volume)',
        '#descPianoVolume': '调节训练营中钢琴提示音的播放音量。<br><b>推荐基准值: 1.0</b>',
        '#labelPlaybackVolume': '录音回放音量 (Playback Volume)',
        '#descPlaybackVolume': '调节录音回放界面的原声播放音量。<br><b>推荐基准值: 1.0</b>',
        '#labelLanguage': '<i data-lucide="languages" class="lucide-icon" style="width: 16px; height: 16px; margin-right: 6px; display: inline-block; vertical-align: middle;"></i>界面语言 (Language)',
        '#descLanguage': '切换界面的显示语言。/ Switch the display language of the interface.',
        '#labelPerformanceMode': '<i data-lucide="zap" class="lucide-icon" style="width: 16px; height: 16px; margin-right: 6px;"></i>前端高性能渲染模式 (Performance Mode)',
        '#descPerformanceMode': '开启后，系统将启用渲染解耦、钢琴卷帘背景 Canvas 离屏缓存、滑动窗口平均算法提速以及双通绘制模拟发声光晕。可极大降低 CPU 负荷与发热。',
        '#settingsModal .btn-ghost': '恢复默认设置',
        '#settingsModal .btn-primary': '确定并应用'
    },
    en: {
        // Top Navigation
        '#tabBtnFree': '<i data-lucide="activity" class="lucide-icon"></i> Real-time Monitor',
        '#tabBtnPro': '<i data-lucide="crown" class="lucide-icon"></i> Pro Features',
        '#btnSettings': '<i data-lucide="sliders" class="lucide-icon"></i> Engine Settings',
        '#btnHelp': '<i data-lucide="help-circle" class="lucide-icon"></i>',
        '#startBtn': '<i data-lucide="zap" class="lucide-icon"></i> Start Engine',
        '#btnCheckUpdate': 'Check Update',
        '#btnInstallUpdate': 'Reinstall & Reboot',
        
        // Workspace Free
        '#freeWorkspace .dashboard-title': 'Acoustic Monitor Data',
        '#btnToggleRecord': '<i data-lucide="circle-dot" class="lucide-icon"></i> Start Record Monitor',
        '#btnPlayPause': '<i data-lucide="play" class="lucide-icon"></i> Play',
        '#btnClosePlayback': '<i data-lucide="x" class="lucide-icon"></i> Close',
        '#btnExportRecord': '<i data-lucide="download" class="lucide-icon"></i> Export',
        '#btnImportRecord': '<i data-lucide="folder-open" class="lucide-icon"></i> Import',
        '#playbackTime': '0.0s / 0.0s',
        '#recordStatusText': 'Recording... 0.0s',
        
        // Free Gauge Titles
        '#titlePitch': 'Pitch',
        '#titleDev': 'Pitch Dev (Cents)',
        '#titleLoud': 'Loudness',
        '#titleBright': 'Resonance (H1/H2)',
        '#titlePure': 'Clarity (HNR)',
        '#titleStab': 'Stability (Jitter)',
        '#trainTitlePitch': 'Pitch',
        '#trainTitleDev': 'Pitch Dev (Cents)',
        '#trainTitleLoud': 'Loudness',
        '#trainTitleBright': 'Resonance (H1/H2)',
        '#trainTitlePure': 'Clarity (HNR)',
        '#trainTitleStab': 'Stability (Jitter)',
        '#descPitch, #trainDescPitch': 'Waiting for voice...',
        '#descDev, #trainDescDev': 'Waiting for voice...',
        '#descLoud, #trainDescLoud': 'Normal',
        '#descBright, #trainDescBright': 'Waiting for voice...',
        '#descPure, #trainDescPure': 'Waiting for voice...',
        '#descStab, #trainDescStab': 'Waiting for voice...',
        
        // Workspace Pro Tabs
        '#btnSubTabSing': '<i data-lucide="mic" class="lucide-icon"></i> Vocal Diagnosis',
        '#btnSubTabTrain': '<i data-lucide="target" class="lucide-icon"></i> Training Camp',
        '#btnSubTabSep': '<i data-lucide="split" class="lucide-icon"></i> Stem Separation',
        
        // Workspace Pro - Sing/Diagnosis
        '#proStateIdle h2': 'Vocal Holographic Diagnosis System',
        '#proStateIdle p': 'Click the button below to record vocals for diagnosis, or import a local audio file to extract diagnosis report in milliseconds.',
        '#btnStartRecord': '<i data-lucide="mic" class="lucide-icon"></i> Real-time Mic Detection',
        '#btnImportAudioDetect': '<i data-lucide="upload" class="lucide-icon"></i> Import Audio Detect',
        '#proStateRecording h2': 'Detecting Vocals... <span id="recordTimer" style="font-family: \'JetBrains Mono\', monospace; color: white;">0.0s</span>',
        '#proStateRecording p': 'Please sing into the microphone. A stable sustained tone or a full phrase is recommended.',
        '#btnStopRecord': '<i data-lucide="square" class="lucide-icon"></i> Stop & Analyze',
        '#proStateReport h2': '<i data-lucide="bar-chart-2" class="lucide-icon"></i> Vocal Diagnosis Report',
        '#btnExportImage': '<i data-lucide="camera" class="lucide-icon"></i> Export Report Image',
        '#btnExportVmap': '<i data-lucide="save" class="lucide-icon"></i> Save as Playback Project',
        '#btnResetRecord': '<i data-lucide="refresh-cw" class="lucide-icon"></i> Restart Detection',
        
        // Workspace Pro - Separation
        '#sepDeviceBar span:first-child': '<i data-lucide="cpu" class="lucide-icon" style="margin-right: 4px;"></i> Run Device:',
        '#btnGPU': '<i data-lucide="zap" class="lucide-icon"></i> GPU Accelerated',
        '#btnCPU': '<i data-lucide="cpu" class="lucide-icon"></i> CPU Compatible',
        '#sepDeviceBar span:last-child': '(Prefer GPU, requires VRAM > 6GB)',
        '#sepPanelsContainer > div:first-child span': '6-Stem Stem Separation',
        '#sepPanelsContainer > div:first-child p': 'Logic-RoFormer professional instrument and stem offline separation',
        '#sepInstUploadZone p:nth-child(2)': 'Choose local audio file',
        '#btnStartSepInst': '<i data-lucide="zap" class="lucide-icon"></i> Start Separation',
        '#sepInstProcessing p:nth-child(2)': 'Separating tracks offline...',
        '#sepInstProcessing p:nth-child(3)': 'The algorithm is executing fast Fourier transform, please wait...',
        '#sepInstResults h3': '<i data-lucide="check" class="lucide-icon"></i> Separation Completed',
        '#btnResetSepInst': 'Reset Console',
        '#sepPanelsContainer > div:last-child span': 'Lead Vocal & Harmony Separation',
        '#sepPanelsContainer > div:last-child p': 'BS-RoFormer high-dimensional convolutional neural network vocal extraction',
        '#sepVocUploadZone p:nth-child(2)': 'Choose local audio file',
        '#btnStartSepVoc': '<i data-lucide="mic" class="lucide-icon"></i> Start Vocal Separation',
        '#sepVocProcessing p:nth-child(2)': 'Separating lead/harmony tracks offline...',
        '#sepVocProcessing p:nth-child(3)': 'Deep learning inference in progress, please wait...',
        '#sepVocResults h3': '<i data-lucide="check" class="lucide-icon"></i> Separation Completed',
        '#btnResetSepVoc': 'Reset Console',
        
        // Workspace Pro - Training
        '#trainingRangeView h2': '<i data-lucide="target" style="color: var(--primary-cyan); margin-right: 8px;"></i>Adaptive Vocal Range Training Camp (Pro)',
        '#trainingRangeView h3': '1. Please select your vocal part and vocal range',
        '.range-card[data-range="soprano"] div:first-child': 'Soprano',
        '.range-card[data-range="mezzo"] div:first-child': 'Mezzo-Soprano',
        '.range-card[data-range="alto"] div:first-child': 'Alto',
        '.range-card[data-range="tenor"] div:first-child': 'Tenor',
        '.range-card[data-range="baritone"] div:first-child': 'Baritone',
        '.range-card[data-range="bass"] div:first-child': 'Bass',
        '.range-card[data-range="custom"] div:first-child': 'Custom Vocal Range',
        '.range-card[data-range="custom"] #customRangeDisplayText': 'Click to set range',
        '#customRangeConfigPanel h4': '<i data-lucide="sliders" style="display: inline-block; width: 16px; height: 16px; vertical-align: middle; margin-right: 6px; margin-top: -2px;"></i>Configure your extreme range',
        '#customRangeConfigPanel label:first-child': 'Lowest Note (Chest Floor)',
        '#customRangeConfigPanel label:nth-child(2)': 'Highest Note (Chest Limit)',
        '#customRangeConfigPanel button': 'Confirm <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-arrow-right"><path d="M5 12h14"/><path d="m12 5 7 7-7 7"/></svg>',
        '#trainingLevelView h2': '<i data-lucide="target" style="color: var(--primary-cyan); margin-right: 8px;"></i>Select level to start training',
        '#trainingLevelView button': '<i data-lucide="chevron-left" class="lucide-icon"></i> Back to Range Selection: <span id="displaySelectedRange" style="color: var(--primary-cyan); font-weight: bold;">--</span>',
        '.level-card[data-level="1"] .level-title': 'Level 1: Warm Up',
        '.level-card[data-level="1"] .level-subtitle': 'Slow warm-up with random major scale up and down',
        '.level-card[data-level="2"] .level-title': 'Level 2: Breath Stability',
        '.level-card[data-level="2"] .level-subtitle': 'Super long note hold, assessing vocal cord control duration',
        '.level-card[data-level="3"] .level-title': 'Level 3: Agility & Riffs',
        '.level-card[data-level="3"] .level-subtitle': 'Dense random pentatonic scales, testing vocal cord transient agility',
        '.level-card[data-level="4"] .level-title': 'Level 4: Intonation Tuning',
        '.level-card[data-level="4"] .level-subtitle': 'Large-interval random leaps, addressing intonation onset issues',
        '.level-card[data-level="5"] .level-title': 'Level 5: Resonance Types',
        '.level-card[data-level="5"] .level-subtitle': 'Vocal range mapping, assessing chest, mixed, and head voice resonance',
        '.level-card[data-level="6"] .level-title': 'Level 6: Grand Challenge',
        '.level-card[data-level="6"] .level-subtitle': '1-minute random full-dimensional acoustic pitch challenge',
        '#trainingActiveLevelName': 'Training: Level 1 Warm Up',
        '#trainingSessionView .score-container span:first-child': 'Current Score:',
        '#trainingSessionView .btn-danger': '<i data-lucide="log-out" class="lucide-icon" style="width: 14px; height: 14px;"></i> Exit Training',
        '#trainingInstructionText': 'Ready',
        
        // Premium Overlay
        '#premiumOverlay h1': 'VocalMap <span style="background: var(--gradient-accent); -webkit-background-clip: text; color: transparent;">Pro</span> Activation',
        '#premiumOverlay p:first-of-type': 'Unlock holographic acoustic diagnosis, radar chart report export, and offline stem separation.',
        '#premiumOverlay div:nth-of-type(1) span': 'Machine hardware fingerprint: ',
        '#premiumOverlay div:nth-of-type(2) span': 'CDK Code:',
        '#btnActivateCDK': '<i data-lucide="key" class="lucide-icon"></i> Activate Pro Privileges',
        '#btnBuyMonthly': '<i data-lucide="calendar" class="lucide-icon"></i> Purchase Monthly Pass <span style="font-size: 24px; font-weight: 800; margin-left: 8px;">￥ 19.9</span>',
        '#btnBuyLifetime': '<i data-lucide="infinity" class="lucide-icon"></i> Purchase Lifetime License <span style="font-size: 24px; font-weight: 800; margin-left: 8px;">￥ 59.9</span>',
        '#btnRefreshStatus': '<i data-lucide="refresh-cw" class="lucide-icon"></i> Re-verify Activation Status',
        
        // Training Result Modal
        '#trainingResultModal h2': 'Training Session Finished',
        '#trainingResultModal p': 'Acoustic feedback of your training is as follows',
        '#trainingResultModal .btn-cyan': 'Confirm and Exit Training Session',
        
        // Help Modal Header
        '#helpModal h2': 'VocalMap User Guide & Diagnosis Manual',
        '#helpTabBtn_intro': '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" data-lucide="zap" aria-hidden="true" class="lucide lucide-zap lucide-icon"><path d="M4 14a1 1 0 0 1-.78-1.63l9.9-10.2a.5.5 0 0 1 .86.46l-1.92 6.02A1 1 0 0 0 13 10h7a1 1 0 0 1 .78 1.63l-9.9 10.2a.5.5 0 0 1-.86-.46l1.92-6.02A1 1 0 0 0 11 14z"></path></svg> Get Started',
        '#helpTabBtn_pro': '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" data-lucide="crown" aria-hidden="true" class="lucide lucide-crown lucide-icon"><path d="M11.562 3.266a.5.5 0 0 1 .876 0L15.39 8.87a1 1 0 0 0 1.516.294L21.183 5.5a.5.5 0 0 1 .798.519l-2.834 10.246a1 1 0 0 1-.956.734H5.81a1 1 0 0 1-.957-.734L2.02 6.02a.5.5 0 0 1 .798-.519l4.276 3.664a1 1 0 0 0 1.516-.294z"></path><path d="M5 21h14"></path></svg> Pro Features',
        '#helpTabBtn_advanced': '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" data-lucide="sliders" aria-hidden="true" class="lucide lucide-sliders lucide-icon"><path d="M10 8h4"></path><path d="M12 21v-9"></path><path d="M12 8V3"></path><path d="M17 16h4"></path><path d="M19 12V3"></path><path d="M19 21v-5"></path><path d="M3 14h4"></path><path d="M5 10V3"></path><path d="M5 21v-7"></path></svg> Tuning Params',
        '#helpTabBtn_faq': '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" data-lucide="message-square" aria-hidden="true" class="lucide lucide-message-square lucide-icon"><path d="M22 17a2 2 0 0 1-2 2H6.828a2 2 0 0 0-1.414.586l-2.202 2.202A.71.71 0 0 1 2 21.286V5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2z"></path></svg> Advanced Tips & FAQ',
        '#helpTabBtn_about': '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" data-lucide="info" aria-hidden="true" class="lucide lucide-info lucide-icon"><circle cx="12" cy="12" r="10"></circle><path d="M12 16v-4"></path><path d="M12 8h.01"></path></svg> About & Feedback',
        '#helpModal .help-modal-footer button': 'Got it, let\'s start',

        '#help_intro_title': 'Real-time Acoustic Monitoring & Feature Analysis',
        '#help_intro_desc': 'VocalMap features a millisecond-level real-time acoustic diagnosis engine. In the "Real-time Monitor" module, you can observe vocal performance dynamically and generate acoustic fingerprint data.',
        '#help_intro_c1_title': '1. Start Monitoring & Recording',
        '#help_intro_c1_desc': 'First click <b>"Start Engine"</b> on the right side of the navigation bar, and then speak or sing into the microphone. The system will plot the pitch trajectory curve with extremely low latency.',
        '#help_intro_c2_title': '2. Zero-latency Project Playback',
        '#help_intro_c2_desc': 'Click <b>"Start Record Monitor"</b> at the bottom left, sing/speak into the microphone, and click <b>"Stop Record"</b>. The playback control bar will automatically appear. You can click play/pause to review your performance, and drag the progress bar to seek. During playback, the view will auto-focus, and the vertical white line will lock to the exact MIDI pitch and score at the current time point.',
        '#help_intro_c3_title': '3. Import & Export (.vmap)',
        '#help_intro_c3_desc': 'After recording, click the <b>"Export"</b> button at the bottom right to pack and save the full audio waveform and acoustic curves as a dedicated `.vmap` project file. You can click <b>"Import"</b> later to restore the session for further review.',
        '#help_intro_title2': 'Acoustic Fingerprint Metrics Description',
        '#help_intro_badge1': 'Pitch',
        '#help_intro_badge1_desc': 'Uses a modified YIN pitch tracking algorithm to capture fundamental frequency in milliseconds and convert it to equal temperament MIDI notes.',
        '#help_intro_badge2': 'Resonance (H1/H2)',
        '#help_intro_badge2_desc': 'Analyzes the relative energy ratio of the fundamental (H1) and first overtone (H2) to evaluate vocal fold closure and resonance depth.',
        '#help_intro_badge3': 'Clarity (HNR)',
        '#help_intro_badge3_desc': 'Harmonics-to-Noise Ratio assessment. Pure tones yield higher values (e.g., above 20dB), whereas hoarseness or breathiness drops the score.',
        '#help_intro_badge4': 'Stability (Jitter)',
        '#help_intro_badge4_desc': 'Microscopic pitch perturbation rate. Evaluates the cycle-to-cycle frequency stability of vocal fold vibration. Keep below 1.5% for general singing.',

        '#help_pro_title': 'Pro Features Operation Guide',
        '#help_pro_desc': 'Professional version unlocks the holographic diagnostic radar brain and the SOTA RoFormer stem separation engine, the ultimate tool for vocal teaching and mixing post-production.',
        '#help_pro_c1_title': '1. Professional Vocal Holographic Diagnosis & Radar Chart',
        '#help_pro_c1_desc': 'In the "Pro Features -&gt; Vocal Diagnosis" subpage, click <b>"Real-time Mic Detection"</b> to record a long phrase, or click <b>"Import Audio Detect"</b> (the algorithm will perform fast offline extraction). Once analyzed, a <b>5D acoustic radar chart</b> will display containing exact stats for pitch accuracy, resonance, clarity, stability, and vibrato.',
        '#help_pro_c2_title': '2. Export High-Definition Report Image',
        '#help_pro_c2_desc': 'Once the diagnosis report is ready, you can click <b>"Export Report Image"</b>. The system will automatically generate a lossless, ultra-high-definition PNG screenshot report, preserving the radar chart and quantitative scores for easy sharing or archiving.',
        '#help_pro_c3_title': '3. Studio-grade High-precision Stem Separation',
        '#help_pro_c3_desc': 'For audio extraction and accompaniment separation, we provide two industry-leading deep learning neural network models:',
        '#help_pro_c3_li1': '<b>6-Stem Separation (Logic-RoFormer)</b>: Separates audio into accompaniment, vocals, drums, bass, piano, guitar, and other independent stems.',
        '#help_pro_c3_li2': '<b>Lead Vocal & Harmony Separation (BS-RoFormer Karaoke)</b>: Removes original lead vocals, extracting clean dry lead vocals and background backing harmonies.',
        '#help_pro_c3_desc_extra': 'You can quickly switch between "GPU Accelerated" (requires VRAM &gt;6GB, extremely fast) and "CPU Compatible" mode at the top of the separation panel.',
        '#help_pro_c4_title': '4. Target Training Camp Dynamic Camera Tracking',
        '#help_pro_c4_desc': 'In "Pro Features -&gt; Training Camp", first select your vocal part (e.g., Soprano, Baritone) and the system will automatically configure your optimal practice vocal range.<br><br><b>Six Advanced Levels include:</b><br>1. <b>Warm Up</b>: Practice pitch accuracy in basic vocal warm-ups.<br>2. <b>Breath Stability</b>: Sustained pitch holding to evaluate long-term vocal cord control.<br>3. <b>Agility & Riffs</b>: Dense pentatonic runs to test transient vocal agility.<br>4. <b>Intonation Tuning</b>: Large-interval random leaps to target onset pitch issues.<br>5. <b>Resonance Types</b>: Vocal range mapping, targeting chest, mixed, and head voice resonance.<br>6. <b>Grand Challenge</b>: 1-minute random full-dimensional acoustic pitch challenge.<br><br><b>Smart View Follow:</b> During training, no manual operation is needed. When hitting extremely high or low notes, the viewport will smoothly pre-scroll to provide the clearest training view.',

        '#help_adv_title': 'Acoustic Engine Bottom Parameters Adjusting Guide',
        '#help_adv_desc': 'Click <b>"Engine Settings"</b> on the top right of the navigation bar to call out the configuration panel. Fine-tuning these three thresholds for different environments and hardware will maximize recognition precision:',
        '#help_adv_c1_title': 'Loudness Activation Gate (Loudness Gate)',
        '#help_adv_c1_desc': '<b>Recommended: 8</b><br>The minimum volume threshold to trigger pitch capture. If you are in a noisy classroom/room or your mic has a strong hum noise floor, increase this value (e.g., 12 to 15) to prevent environmental sounds from triggering the dashboard.',
        '#help_adv_c2_title': 'Vocal Clarity Threshold (Clarity Threshold)',
        '#help_adv_c2_desc': '<b>Recommended: 0.65</b><br>Controls capture sensitivity to breathy phonation, vocal fry, or breathing sounds. For humming, soft singing, or edge vibration (vocal fry) measurements, reduce this value (e.g., 0.4 to 0.5). For general live singing, keep at 0.65 or higher to filter breathing airflows.',
        '#help_adv_c3_title': 'Noise Tracking Threshold (Noise Tracking)',
        '#help_adv_c3_desc': '<b>Recommended: 20</b><br>Controls the noise reduction tracker depth. When ambient noise or background music falls below this point, the noise tracker deems the singer silent and silences the input within milliseconds. This prevents clutter points from appearing at pitch curve tails.',

        '#help_faq_title': 'Advanced Techniques for Vocal Teaching & Analysis',
        '#help_faq_t1_strong_txt': 'Ultimate Vocal Secret: How to perfectly measure a singer\'s exact pitch in any existing song?',
        '#help_faq_t1_desc1': 'Commercial tracks contain loud orchestral, guitar, or drum accompaniments. If imported directly to acoustic monitoring, instrument frequencies will heavily interfere with the YIN tracker, causing pitch curves to jump wildly or fail to lock.',
        '#help_faq_t1_bold_txt': 'Perfect Workflow Solution',
        '#help_faq_t1_desc2': 'First, import the track into <b>Pro Features -&gt; Stem Separation</b>, run <b>"Lead Vocal & Harmony Separation"</b>, and save the pure vocals stem locally. Then, import this vocals WAV file via <b>Vocal Diagnosis -&gt; Import Audio Detect -&gt; Save as Playback Project -&gt; Real-time Monitor -&gt; Import</b>. The system will measure a smooth, interference-free, 100% accurate physical pitch and vibrato trajectory of the singer!',
        '#help_faq_t2_strong_txt': 'Target Score Conversion Mechanism',
        '#help_faq_t2_desc': 'Training camp scores evaluate both absolute intonation and include dynamic deductions for <b>transient response time</b> and <b>stability</b>. Hitting the center of target blocks and sustaining it yields full scores; drifting at borders or shaking (high Jitter) dynamically reduces scores. High-frequency practice with this mechanism significantly improves vocal cord closure control.',
        '#help_faq_t3_strong_txt': 'Soprano/Baritone Vocal Parts Physical Resonance Reference Table',
        '#help_faq_t3_desc': 'Each voice part has a different physical resonance focus when traversing the chest-head register break (Passaggio). For example, <b>Soprano</b> passaggio is usually around F#5, chest voice mainly C4-F4, and head voice targets above C5; whereas <b>Baritone</b> passaggio falls on Eb4-E4, making G2-C3 chest zone critical for consolidating lower mechanism. You can practice this mapping in "Resonance Types" training levels.',
        '#help_faq_qa_heading': 'FAQ',
        '#help_faq_q1_title': 'Q: How long does it take for the first run or inference of Stem Separation?',
        '#help_faq_q1_desc': 'A: All core AI model weights and portable inference libraries <b>have been fully downloaded and verified by the built-in download manager on first run</b>. When starting inference for the first time, the Python engine takes a brief moment to load the model from disk to VRAM/RAM. Once loaded, subsequent separation runs are fully local, lightning-fast offline inferences.',
        '#help_faq_q2_title': 'Q: Why does saving or downloading always freeze after stem separation?',
        '#help_faq_q2_desc': 'A: Previous Tauri JS-to-Rust binary bridges caused temporary UI freezes when transferring massive lossless WAV files. VocalMap v2.8.2 introduced <b>local FastAPI Zero-Copy direct writing</b>. Separated stems are written directly to the target disk by the Python engine at physical speed, completely eliminating RAM overload and UI sluggishness. Relaunching/updating resolves this issue.',
        '#help_faq_q3_title': 'Q: Why is the version number missing, or the UI feels frozen?',
        '#help_faq_q3_desc': 'A: This usually indicates that the local Python diagnostic engine is blocked by security software (e.g., 360 or Windows Defender), or the WebSocket communication port (5050) is occupied by other local proxy tools. Please add the app to your antivirus whitelist and ensure port 5050 is free.',

        '#help_about_title': 'Version, License Activation & Feedback',
        '#help_about_c1_title': 'VocalMap Pro Activation',
        '#help_about_c1_desc': 'To protect proprietary core algorithms, advanced holographic diagnostics and stem separation are locked to hardware bindings. You can view your machine\'s <b>"Hardware Fingerprint"</b> in the Pro activation panel, purchase a monthly pass or lifetime CDK via official channels, and paste it to activate. Cloud servers will issue a local offline license certificate instantly.',
        '#help_about_c2_title': 'OTA Silent Auto-Update',
        '#help_about_c2_desc': 'In the top navigation bar, click <b>"Check Update"</b>. The updater connects to a high-speed distribution network. Once a new version is found, it downloads asynchronously in the background. Simply click <b>"Reinstall & Reboot"</b> to replace the main binary seamlessly, keeping your core AI models and acoustic algorithms at the bleeding edge!',
        '#help_about_c3_title': 'Encountered a system failure? One-click GitHub Feedback',
        '#help_about_c3_desc': 'Incompatible sound card driver, neural network crash, or suggestions for improving acoustic fingerprints? Feel free to click the button below to submit an issue on our official open-source community, and the dev team will respond promptly!',
        '#help_about_btn': '<i data-lucide="github" class="lucide-icon"></i> Submit Feedback & Bug Logs on GitHub',
        
        // Settings Modal
        '#settingsModal h2': '<i data-lucide="sliders" class="lucide-icon"></i> Advanced Acoustic Engine Settings',
        '#labelMicrophone': 'Microphone Input Device (Microphone)',
        '#descMicrophone': 'Choose the microphone hardware device used for recording and singing. Restarting the acoustic engine is recommended after change.',
        '#labelLoudnessGate': 'Loudness Activation Gate (Loudness Gate)',
        '#descLoudnessGate': 'Minimum volume threshold to trigger pitch capture. If ambient noise is high, increase this value (e.g. 15-20) to prevent false triggering.<br><b>Recommended: 12</b>',
        '#labelClarityThreshold': 'Vocal Clarity Threshold (Clarity Threshold)',
        '#descClarityThreshold': 'Controls capture sensitivity to breathy/vocal fry/weak phonation. For weak edge vibration or humming, decrease this value (e.g. 0.4-0.5).<br><b>Recommended: 0.65</b>',
        '#labelNoiseTracking': 'Noise Tracking Threshold (Noise Tracking)',
        '#descNoiseTracking': 'Noise reduction tracking depth. Input below this threshold is treated as silence and forced to zero to prevent tail clutter in pitch curves.<br><b>Recommended: 20</b>',
        '#labelPianoVolume': 'Piano Guide Volume (Piano Volume)',
        '#descPianoVolume': 'Adjust piano prompt volume in the training camp.<br><b>Recommended: 1.0</b>',
        '#labelPlaybackVolume': 'Playback Volume (Playback Volume)',
        '#descPlaybackVolume': 'Adjust playback volume for recorded vocals.<br><b>Recommended: 1.0</b>',
        '#labelLanguage': '<i data-lucide="languages" class="lucide-icon" style="width: 16px; height: 16px; margin-right: 6px; display: inline-block; vertical-align: middle;"></i>Interface Language (Language)',
        '#descLanguage': 'Switch the display language of the interface.',
        '#labelPerformanceMode': '<i data-lucide="zap" class="lucide-icon" style="width: 16px; height: 16px; margin-right: 6px;"></i>High Performance Rendering Mode (Performance Mode)',
        '#descPerformanceMode': 'When enabled, the system uses rendering decoupling, piano roll background Canvas off-screen cache, moving average speedup, and dual-pass rendering. Greatly reduces CPU load and heat.',
        '#settingsModal .btn-ghost': 'Restore Defaults',
        '#settingsModal .btn-primary': 'Confirm & Apply'
    }
};

const JS_DICTIONARY = {
    zh: {
        'audio.default_device': '系统默认设备 (Default)',
        'audio.mic_label': '麦克风',
        'audio.no_devices': '无法获取设备列表',
        'audio.vc_redist_warning': '⚠️ 严重环境缺失：\n\n检测到您的系统未安装微软 C++ 运行库 (VC++ 2015-2022 Redistributable)。\n\nVocalMap 的音频核心需要此底层环境才能运行。\n\n点击【确定】将自动为您打开微软官方下载链接，请下载并安装 x64 版本后，重新启动本软件！',
        'audio.backend_connected': '连接状态: 已连接',
        'audio.backend_disconnected': '连接状态: 已断开',
        'audio.mic_access_failed_title': '麦克风访问失败',
        'audio.mic_access_failed_msg': '无法访问您的音频输入设备: ',
        'audio.mic_access_failed_alert': '无法访问麦克风: ',
        'audio.engine_start_failed_title': '引擎启动失败',
        'audio.engine_start_failed_msg': '无法连接麦克风或后端分析引擎，请检查后端服务是否正在运行！',
        'audio.training_terminated_title': '训练已终止',
        'audio.training_terminated_msg': '后端引擎已断开，当前训练被强制终止。',
        'audio.stop_engine': '<i data-lucide="square" class="lucide-icon"></i> 停止引擎 / Stop',
        'audio.start_engine': '<i data-lucide="zap" class="lucide-icon"></i> 启动引擎',
        
        'monitor.waiting': '等待发声...',
        'monitor.loud_normal': '🗣️ 正常音量',
        'monitor.loud_soft': '🤫 轻声',
        'monitor.loud_loud': '💥 强音/爆音',
        'monitor.loud_active': '正常',
        'monitor.bright_head': '🟡 头声主导',
        'monitor.bright_chest': '🟠 胸声主导',
        'monitor.bright_mix': '🔵 混声',
        'monitor.bright_waiting': '等待持续发声...',
        'monitor.pure_tight': '🛡️ 闭合紧密',
        'monitor.pure_breathy': '💨 气声漏气',
        'monitor.pure_focused': '🎵 声音集中',
        'monitor.stab_straight': '➖ 平稳长直',
        'monitor.stab_jitter': '⚠️ 震荡',
        'monitor.stab_vibrato': '🌊 颤音自然',
        'monitor.dev_sharp': '🔺 偏高 (Sharp)',
        'monitor.dev_flat': '🔻 偏低 (Flat)',
        'monitor.dev_hit': '✅ 命中靶心',
        'monitor.record_start': '<i data-lucide="square" class="lucide-icon"></i> 停止监视录制',
        'monitor.record_stop': '<i data-lucide="circle-dot" class="lucide-icon"></i> 开始监视录制',
        'monitor.record_engine_warning': '请先启动右上角声学引擎，建立麦克风桥接后再开启录制！',
        'monitor.record_engine_warning_title': '引擎未就绪',
        'monitor.playback_play': '<i data-lucide="play" class="lucide-icon"></i> 播放',
        'monitor.playback_pause': '<i data-lucide="pause" class="lucide-icon"></i> 暂停',
        'monitor.rec_status_text': '录制中... ',
        
        'diag.mic_warn_title': '全息诊断警告',
        'diag.mic_warn_msg': '全息全录诊断舱需要先启动声学系统。请先点击右上角【连接后端并启动】按钮！',
        'diag.import_warn_msg': '导入全长音频进行一键诊断需要先启动声学引擎，打通底层检测服务通道！',
        'diag.processing': '🚀 正在进行离线高速分析，请稍候...',
        'diag.process_failed': '分析失败: 未知返回格式',
        'diag.analyzing_rec': '正在综合分析刚才的演唱数据，请稍候...',
        'diag.library_loading': '长图导出库尚未加载完成，请稍后再试！',
        'diag.image_exporting_overlay': '正在为您提取原生高精度图像...',
        'diag.export_success': '报告长图导出成功！\n已保存至: ',
        'diag.export_failed': '保存长图失败: ',
        'diag.no_data': '无法导出：缺少音频录制数据或时间轴数据。',
        'diag.not_desktop': '非桌面端环境，无法使用原生导出',
        'diag.export_vmap_success': '导出成功！已保存:\n',
        'diag.radar_accuracy': '音准',
        'diag.radar_stability': '稳定',
        'diag.radar_purity': '纯净',
        'diag.radar_resonance': '共鸣',
        'diag.radar_vibrato': '颤音',
        'diag.report_findings': '诊断发现',
        'diag.report_insights': '多维交叉洞察',
        'diag.report_normal': '各项指标均在正常范围，未发现明显问题。',
        'diag.report_duration': '录制时长',
        'diag.report_data_size': '数据量',
        'diag.report_unavailable': '报告数据不可用，请重新录制。',
        'diag.insufficient_data': '有效发声数据不足，请大声演唱并保持足够时长。',
        'diag.license_missing': '未找到许可证文件。请先购买 Pro 版并激活。',
        'diag.license_expired': '您的许可证已过期，请续费。',
        'diag.license_invalid': '许可证验证失败，请重新激活。',
        
        'sep.dl_title': '初始化 AI 分离引擎',
        'sep.dl_desc': '首次使用音轨分离功能需要下载运行环境及模型权重。<br>这包含 PyTorch、CUDA 加速库以及两个高性能模型（总计约 5GB）。<br>下载时间取决于您的网速，请保持网络畅通。',
        'sep.dl_btn_dl': '🚀 立即开始下载 (5GB)',
        'sep.dl_btn_later': '以后再说，返回主界面',
        'sep.dl_preparing': '准备下载...',
        'sep.dl_success': '✅ 下载部署完成！正在进入系统...',
        'sep.dl_failed': '❌ 下载失败: ',
        'sep.dl_close_retry': '关闭并重试',
        'sep.cpu_processing': 'CPU 处理中...',
        'sep.uploading_processing': '上传并推理中...',
        'sep.model_loading': '模型初始化中，请稍候...',
        'sep.model_running': '模型推理中，进度: ',
        'sep.model_running_wait': '模型推理中，请耐心等待...',
        'sep.task_error': '分离出错: ',
        'sep.request_failed': '请求失败: ',
        
        'sep.stem.bass': '贝斯',
        'sep.stem.drums': '鼓组',
        'sep.stem.vocals': '人声',
        'sep.stem.other': '其他',
        'sep.stem.guitar': '吉他',
        'sep.stem.piano': '钢琴',
        'sep.stem.instrumental': '纯伴奏',
        'sep.stem.voc_harmony': '伴奏与和声',
        'sep.stem.voc_lead': '人声',
        'sep.write_wav': '下载 WAV',
        'sep.writing': '写入中...',
        'sep.write_success': '写入成功',
        'sep.write_failed': '下载失败',
        
        'train.lowest_highest_alert': '最高音必须高于最低音！',
        'train.mic_warn_title': '全息舱检测警告',
        'train.mic_warn_msg': '检测到系统引擎尚未就绪。请先点击右上角【连接后端并启动】按钮，打通声学网关！',
        'train.level_1': '热身激活',
        'train.level_2': '气息稳定',
        'train.level_3': '转音练习',
        'train.level_4': '音准精修',
        'train.level_5': '三类共鸣',
        'train.level_6': '综合挑战',
        'train.soprano': '女高音',
        'train.mezzo': '女中音',
        'train.alto': '女低音',
        'train.tenor': '男高音',
        'train.baritone': '男中音',
        'train.bass': '男低音',
        'train.custom': '自定义',
        
        'train.inst.warmup_long': '平稳长音，调整呼吸',
        'train.inst.warmup_climb': '顺阶上行，唤醒声带',
        'train.inst.warmup_down': '顺阶下行',
        'train.inst.warmup_hold': '落音稳住气息',
        'train.inst.warmup_arp_up': '琶音上行，打开共鸣腔',
        'train.inst.warmup_arp_down': '琶音下行',
        'train.inst.stability_hold': '稳定长音，保持核心支撑',
        'train.inst.riff_relax': '丝滑布鲁斯转音，放松喉头',
        'train.inst.riff_hold': '稳定落音',
        'train.inst.riff_light': '轻盈上行，寻找高位共鸣',
        'train.inst.riff_wave': '波浪转音，灵活折返',
        'train.inst.riff_back': '回到基准',
        'train.inst.precision_prepare': '定音准备，音准聚焦',
        'train.inst.precision_jump': '高跨度跳跃，精准打击',
        'train.inst.resonance_chest': '底音区目标，打开胸声共鸣',
        'train.inst.resonance_mix': '换声区目标，使用混声建立连接',
        'train.inst.resonance_head': '高音区目标，释放明亮的头声',
        'train.inst.resonance_head_limit': '高音区极限挑战，释放头声',
        'train.inst.riff_fast_down': '极速下行转音',
        'train.inst.riff_fast_up': '极速上行转音',
        'train.inst.riff_fast_wave': '波浪转音',
        'train.inst.hold_stable': '着陆稳住',
        
        'train.feedback.perfect': '<b style="color: #00E676;"><i data-lucide="check-circle" class="lucide-icon" style="width:16px;height:16px;"></i> 完美驾驭！</b><br>您的气息支撑和音准控制堪称专业级表现，共鸣通道完全打开。可以尝试更高难度的挑战或跨音区练习了！',
        'train.feedback.good': '<b style="color: #00B0FF;"><i data-lucide="thumbs-up" class="lucide-icon" style="width:16px;height:16px;"></i> 表现优秀！</b><br>您已经掌握了该关卡的核心发声技巧。但在长音稳定度或音阶切换的瞬间还可以更加平滑，继续保持练习！',
        'train.feedback.average': '<b style="color: #FFEA00;"><i data-lucide="alert-circle" class="lucide-icon" style="width:16px;height:16px;"></i> 潜力很大！</b><br>音准大方向是正确的，但在特定靶向区间出现了气息不稳或音高游离。建议先退回上一关进行慢速的热身巩固。',
        'train.feedback.poor': '<b style="color: #FF5252;"><i data-lucide="info" class="lucide-icon" style="width:16px;height:16px;"></i> 需要调整！</b><br>音准偏差较大，可能是发声机能尚未唤醒或音区选择不匹配。别灰心，建议重新选择您的核心音区，从最基础的长直音开始练起。',
        
        'train.tutorial.level1': '【热身激活】目标是唤醒声带。得分的关键在于<b>放松喉头</b>，不要追求音量，而是追求在每个音符转换时的平滑度与音高的准确命中。',
        'train.tutorial.level2': '【气息稳定】得分的关键是<b>控制呼气的均匀度</b>。在超长音期间，请使用横膈膜支撑，保持发光线条（稳定度 Stab）笔直，不要让声音发抖。',
        'train.tutorial.level3': '【转音练习】得分的关键在于<b>颗粒感</b>。遇到密集的下行音阶，切忌滑音拖沓。可以在练习时加入微弱的“弹”的感觉，确保每个音都能单独被识别框捕获。',
        'train.tutorial.level4': '【音准精修】面对大跨度跳跃，不要在滑动中寻找音高。得分秘诀是：在心里提前“听”到目标音，然后用气息<b>直接精准降落</b>在目标矩形内。',
        'train.tutorial.level5': '【三类共鸣】得分要求不仅是音准！底音区需要您提高胸腔震动（声带闭合严实）；中音区需结合面罩共鸣；高音区需放松下巴，让气流冲击头腔（提升亮度 Brightness）。',
        'train.tutorial.level6': '【综合挑战】这不仅考核声乐机能，更考核体力。高分的秘诀是学会<b>在间隙合理偷气</b>，在转音时收力，在长音时使用核心对抗。',
        
        'pay.browser_env': '浏览器测试环境 (请在桌面客户端运行)',
        'pay.activated_lifetime': '已激活 (永久版)',
        'pay.activated_monthly': '已激活 (月度版)',
        'pay.enter_cdk': '请输入激活码',
        'pay.invalid_format': '激活码格式不正确，应为 VMAP-XXXX-XXXX-XXXX',
        'pay.verifying': '正在验证激活码...',
        'pay.success': '激活成功！',
        'pay.failed': '激活失败',
        'pay.server_error': '无法连接许可证服务器，请检查网络。',
        'pay.refreshing': '正在刷新许可证状态...',
        'pay.license_valid': '许可证有效，已解锁 Pro 功能。',
        'pay.license_invalid': '尚未激活，请购买或输入激活码。',
        'pay.generating_gateway': '正在生成支付通道...',
        'pay.order_created': '已打开浏览器支付页面。支付完成后请点击【刷新许可证状态】。',
        'pay.blocked_popup': '网页环境拦截跳转，链接: ',
        'pay.cloud_failed': '云端连接失败，请检查网络。',
        'train.active_level_prefix': '正在进行: 关卡 ',
        'pay.failed_prefix': '失败：'
    },
    en: {
        'audio.default_device': 'Default Audio Input Device',
        'audio.mic_label': 'Microphone',
        'audio.no_devices': 'Failed to get device list',
        'audio.vc_redist_warning': '⚠️ Missing Environment:\n\nMicrosoft C++ Redistributable (VC++ 2015-2022) is not installed.\n\nVocalMap needs this environment to run the audio core.\n\nClick [OK] to download the x64 version, and restart the software after installation!',
        'audio.backend_connected': 'Backend: Connected',
        'audio.backend_disconnected': 'Backend: Disconnected',
        'audio.mic_access_failed_title': 'Mic Access Failed',
        'audio.mic_access_failed_msg': 'Cannot access your audio device: ',
        'audio.mic_access_failed_alert': 'Mic access failed: ',
        'audio.engine_start_failed_title': 'Engine Start Failed',
        'audio.engine_start_failed_msg': 'Cannot connect to backend analyzer engine. Check if backend service is running!',
        'audio.training_terminated_title': 'Training Terminated',
        'audio.training_terminated_msg': 'Backend engine disconnected. Training forced to terminate.',
        'audio.stop_engine': '<i data-lucide="square" class="lucide-icon"></i> Stop Engine',
        'audio.start_engine': '<i data-lucide="zap" class="lucide-icon"></i> Start Engine',
        
        'monitor.waiting': 'Waiting for voice...',
        'monitor.loud_normal': '🗣️ Normal Volume',
        'monitor.loud_soft': '🤫 Soft Voice',
        'monitor.loud_loud': '💥 Loud / Clipping',
        'monitor.loud_active': 'Active',
        'monitor.bright_head': '🟡 Head Voice',
        'monitor.bright_chest': '🟠 Chest Voice',
        'monitor.bright_mix': '🔵 Mixed Voice',
        'monitor.bright_waiting': 'Waiting for sound...',
        'monitor.pure_tight': '🛡️ Firm Phonation',
        'monitor.pure_breathy': '💨 Breathy Phonation',
        'monitor.pure_focused': '🎵 Focused Tone',
        'monitor.stab_straight': '➖ Flat & Stable',
        'monitor.stab_jitter': '⚠️ Jitter / Shake',
        'monitor.stab_vibrato': '🌊 Natural Vibrato',
        'monitor.dev_sharp': '🔺 Sharp (+)',
        'monitor.dev_flat': '🔻 Flat (-)',
        'monitor.dev_hit': '✅ Bullseye',
        'monitor.record_start': '<i data-lucide="square" class="lucide-icon"></i> Stop Record',
        'monitor.record_stop': '<i data-lucide="circle-dot" class="lucide-icon"></i> Start Record',
        'monitor.record_engine_warning': 'Please start the acoustic engine first to establish microphone bridging!',
        'monitor.record_engine_warning_title': 'Engine Offline',
        'monitor.playback_play': '<i data-lucide="play" class="lucide-icon"></i> Play',
        'monitor.playback_pause': '<i data-lucide="pause" class="lucide-icon"></i> Pause',
        'monitor.rec_status_text': 'Recording... ',
        
        'diag.mic_warn_title': 'Diagnosis Warning',
        'diag.mic_warn_msg': 'Holographic diagnosis requires active acoustic engine. Click [Start Engine] first!',
        'diag.import_warn_msg': 'Importing audio requires starting the acoustic engine to establish service channel!',
        'diag.processing': '🚀 Performing high-speed offline analysis, please wait...',
        'diag.process_failed': 'Analysis failed: Unknown response format',
        'diag.analyzing_rec': 'Analyzing vocal performance metrics, please wait...',
        'diag.library_loading': 'Image library is still loading, please try again later!',
        'diag.image_exporting_overlay': 'Generating high-definition report image...',
        'diag.export_success': 'Report image exported successfully!\nSaved to: ',
        'diag.export_failed': 'Failed to save image: ',
        'diag.no_data': 'Export failed: Missing audio recording or timeline data.',
        'diag.not_desktop': 'Non-desktop environment. Native export not supported.',
        'diag.export_vmap_success': 'Export succeeded! Saved to:\n',
        'diag.radar_accuracy': 'Accuracy',
        'diag.radar_stability': 'Stability',
        'diag.radar_purity': 'Clarity',
        'diag.radar_resonance': 'Resonance',
        'diag.radar_vibrato': 'Vibrato',
        'diag.report_findings': 'Diagnosis Findings',
        'diag.report_insights': 'Cross Insights',
        'diag.report_normal': 'All metrics are within normal ranges. No significant issues found.',
        'diag.report_duration': 'Duration',
        'diag.report_data_size': 'Data Size',
        'diag.report_unavailable': 'Report data unavailable, please record again.',
        'diag.insufficient_data': 'Insufficient vocal data. Please sing louder and maintain for a longer duration.',
        'diag.license_missing': 'License file not found. Please purchase Pro version and activate it first.',
        'diag.license_expired': 'Your license has expired, please renew.',
        'diag.license_invalid': 'License verification failed, please reactivate.',
        
        'sep.dl_title': 'Initialize AI Stem Engine',
        'sep.dl_desc': 'Stem separation requires downloading dependencies and weights on first run.<br>Includes PyTorch, CUDA libraries, and two neural models (~5GB total).<br>Download speed depends on your connection. Keep internet active.',
        'sep.dl_btn_dl': '🚀 Start Download (5GB)',
        'sep.dl_btn_later': 'Later, Back to Main',
        'sep.dl_preparing': 'Preparing download...',
        'sep.dl_success': '✅ Setup complete! Redirecting...',
        'sep.dl_failed': '❌ Download failed: ',
        'sep.dl_close_retry': 'Close and Retry',
        'sep.cpu_processing': 'CPU Processing...',
        'sep.uploading_processing': 'Uploading & Inferencing...',
        'sep.model_loading': 'Initializing model weights, please wait...',
        'sep.model_running': 'Processing, progress: ',
        'sep.model_running_wait': 'Neural network processing, please wait...',
        'sep.task_error': 'Separation error: ',
        'sep.request_failed': 'Request failed: ',
        
        'sep.stem.bass': 'Bass',
        'sep.stem.drums': 'Drums',
        'sep.stem.vocals': 'Vocals',
        'sep.stem.other': 'Other Stems',
        'sep.stem.guitar': 'Guitar',
        'sep.stem.piano': 'Piano',
        'sep.stem.instrumental': 'Instrumental',
        'sep.stem.voc_harmony': 'Accompaniment & Backing',
        'sep.stem.voc_lead': 'Lead Vocals',
        'sep.write_wav': 'Download WAV',
        'sep.writing': 'Writing...',
        'sep.write_success': 'Write Success',
        'sep.write_failed': 'Download Failed',
        
        'train.lowest_highest_alert': 'Highest pitch must be higher than lowest pitch!',
        'train.mic_warn_title': 'Training Chamber Warning',
        'train.mic_warn_msg': 'Acoustic engine is offline. Start the engine to establish microphone connection first!',
        'train.level_1': 'Warm Up',
        'train.level_2': 'Breath Stability',
        'train.level_3': 'Agility & Riffs',
        'train.level_4': 'Intonation Tuning',
        'train.level_5': 'Resonance Types',
        'train.level_6': 'Grand Challenge',
        'train.soprano': 'Soprano',
        'train.mezzo': 'Mezzo-Soprano',
        'train.alto': 'Alto',
        'train.tenor': 'Tenor',
        'train.baritone': 'Baritone',
        'train.bass': 'Bass',
        'train.custom': 'Custom',
        
        'train.inst.warmup_long': 'Steady long tone, adjust breathing',
        'train.inst.warmup_climb': 'Diatonic climb, wake up vocal cords',
        'train.inst.warmup_down': 'Diatonic scale down',
        'train.inst.warmup_hold': 'Sustained landing tone',
        'train.inst.warmup_arp_up': 'Arpeggio up, open resonance chambers',
        'train.inst.warmup_arp_down': 'Arpeggio down',
        'train.inst.stability_hold': 'Steady long tone, keep core support active',
        'train.inst.riff_relax': 'Smooth blues riff, relax larynx',
        'train.inst.riff_hold': 'Steady ending tone',
        'train.inst.riff_light': 'Light agility climb, find high resonance',
        'train.inst.riff_wave': 'Wave-like riffs, flexible turnarounds',
        'train.inst.riff_back': 'Return to root note',
        'train.inst.precision_prepare': 'Pitch centering preparation',
        'train.inst.precision_jump': 'Large leap target, center pitch directly',
        'train.inst.resonance_chest': 'Low range target, open chest resonance',
        'train.inst.resonance_mix': 'Passaggio target, connect mixed register',
        'train.inst.resonance_head': 'High range target, release head resonance',
        'train.inst.resonance_head_limit': 'Extreme high range, release head voice',
        'train.inst.riff_fast_down': 'Fast down-scale agility run',
        'train.inst.riff_fast_up': 'Fast up-scale agility run',
        'train.inst.riff_fast_wave': 'Wave agility riffs',
        'train.inst.hold_stable': 'Stabilize landing note',
        
        'train.feedback.perfect': '<b style="color: #00E676;"><i data-lucide="check-circle" class="lucide-icon" style="width:16px;height:16px;"></i> Perfect Control!</b><br>Your breath support and intonation accuracy are highly professional. The resonance channels are fully open. Feel free to try harder challenges or wider ranges!',
        'train.good': 'Great Job!',
        'train.feedback.good': '<b style="color: #00B0FF;"><i data-lucide="thumbs-up" class="lucide-icon" style="width:16px;height:16px;"></i> Great Job!</b><br>You have mastered the core technique of this level. Try to make note transitions even smoother in upcoming sessions!',
        'train.feedback.average': '<b style="color: #FFEA00;"><i data-lucide="alert-circle" class="lucide-icon" style="width:16px;height:16px;"></i> Great Potential!</b><br>Overall pitch direction is correct, but breath jitter or pitch drift occurred at target boundaries. Consolidated warmups are recommended.',
        'train.feedback.poor': '<b style="color: #FF5252;"><i data-lucide="info" class="lucide-icon" style="width:16px;height:16px;"></i> Needs Adjustment!</b><br>Major pitch deviation detected. Your vocal mechanism might not be fully warmed up. Try choosing a matching range and start from basic straight notes.',
        
        'train.tutorial.level1': '[Warm Up] designed to wake up vocal folds. Focus on relaxing your throat and aim for smooth, tension-free note transitions rather than volume.',
        'train.tutorial.level2': '[Breath Stability] focuses on even exhalation. Use your diaphragm to support long notes, keeping the stability line (Stab) completely flat without shaking.',
        'train.tutorial.level3': '[Agility & Riffs] score depends on note definition. Avoid slurring during fast scales; add a light "pulsing" feel so every pitch is captured in the target boxes.',
        'train.tutorial.level4': '[Intonation Tuning] for large leaps. Do not scoop into the pitch; hear the target tone in your mind beforehand, then drop your voice directly in the box.',
        'train.tutorial.level5': '[Resonance Types] tests your registration. Low zones require firm vocal cord closure (chest); mid zones need mask resonance; high zones require relaxing your jaw and utilizing head voice.',
        'train.tutorial.level6': '[Grand Challenge] tests physical endurance. The key to high scores is capturing quick breaths during rests, pacing your energy, and engaging your core on sustained notes.',
        
        'pay.browser_env': 'Browser Sandbox Environment (Please run desktop client)',
        'pay.activated_lifetime': 'Activated (Lifetime License)',
        'pay.activated_monthly': 'Activated (Monthly Pass)',
        'pay.enter_cdk': 'Please enter CDK activation code',
        'pay.invalid_format': 'Invalid CDK format. Expected VMAP-XXXX-XXXX-XXXX',
        'pay.verifying': 'Verifying code status...',
        'pay.success': 'Activation succeeded!',
        'pay.failed': 'Activation failed',
        'pay.server_error': 'Failed to connect to license server, check network.',
        'pay.refreshing': 'Refreshing license status...',
        'pay.license_valid': 'License valid. Pro features unlocked.',
        'pay.license_invalid': 'Not activated. Purchase or enter a valid CDK.',
        'pay.generating_gateway': 'Opening payment gateway...',
        'pay.order_created': 'Payment page opened in browser. Click [Re-verify Status] after checkout.',
        'pay.blocked_popup': 'Popup blocked by browser. Direct link: ',
        'pay.cloud_failed': 'Failed to connect to billing cloud. Check network.',
        'train.active_level_prefix': 'Training: Level ',
        'pay.failed_prefix': 'Failed: ',
        '[听音提示] ': '[Listening Hint] ',
        '平稳长音，调整呼吸': 'Steady long tone, adjust breathing',
        '顺阶上行，唤醒声带': 'Diatonic scale up, wake up vocal folds',
        '顺阶上行': 'Diatonic scale up',
        '顺阶下行': 'Diatonic scale down',
        '落音稳住气息': 'Sustained landing tone',
        '琶音上行，打开共鸣腔': 'Arpeggio up, open resonance chambers',
        '琶音下行': 'Arpeggio down',
        '稳定长音，保持核心支撑': 'Steady long tone, keep core support active',
        '丝滑布鲁斯转音，放松喉头': 'Smooth blues riff, relax larynx',
        '稳定落音': 'Steady ending tone',
        '轻盈上行，寻找高位共鸣': 'Light agility climb, find high resonance',
        '波浪转音，灵活折返': 'Wave-like riffs, flexible turnarounds',
        '回到基准': 'Return to root note',
        '定音准备，音准聚焦': 'Pitch centering preparation',
        '高跨度跳跃，精准打击': 'Large leap target, center pitch directly',
        '底音区目标，打开胸声共鸣': 'Low range target, open chest resonance',
        '换声区目标，使用混声建立连接': 'Passaggio target, connect mixed register',
        '高音区目标，释放明亮的头声': 'High range target, release head resonance',
        '高音区极限挑战，释放头声': 'Extreme high range, release head voice',
        '极速下行转音': 'Fast down-scale agility run',
        '极速上行转音': 'Fast up-scale agility run',
        '波浪转音': 'Wave agility riffs',
        '着陆稳住': 'Stabilize landing note',
        '平稳发声，深呼吸': 'Steady phonation, breathe deeply',
        'update.checking': 'Checking for updates...',
        'update.download': 'Download Update',
        'update.found_prefix': 'New version v',
        'update.found_suffix': ' found, click to download',
        'update.latest': 'Already up-to-date',
        'update.check_failed': 'Update check failed: ',
        'update.downloading': 'Downloading...',
        'update.downloading_pct': 'Downloading ',
        'update.download_success_prefix': 'v',
        'update.download_success_suffix': ' downloaded, click to install & relaunch',
        'update.install': 'Install & Relaunch',
        'update.download_failed': 'Download failed: ',
        'update.redownload': 'Retry Download',
        'update.installing': 'Installing...',
        'update.installing_status': 'Installing update, preparing to relaunch...',
        'update.install_failed': 'Installation failed: ',
        'update.reinstall': 'Retry Install',
        'update.check_btn': 'Check Update',
        'update.install_btn': 'Reinstall & Reboot',
        'monitor.engine_unready_alert': 'Please start the engine before recording!',
        'monitor.no_record_data': 'No complete recording data available',
        'monitor.export_failed': 'Export failed: ',
        'monitor.import_failed': 'Import failed or audio file missing: ',
        'train.finished_alert_prefix': 'Training completed! Final score: ',
        'train.modal_error': 'Training completed! (Error displaying score panel)'
    }
};

window.LANG_DICTIONARY = LANG_DICTIONARY;
window.JS_DICTIONARY = JS_DICTIONARY;

window.t = function(key, defaultValue) {
    const currentLang = localStorage.getItem('vmap_set_lang') || 'zh';
    if (JS_DICTIONARY[currentLang] && JS_DICTIONARY[currentLang][key]) {
        return JS_DICTIONARY[currentLang][key];
    }
    return defaultValue || key;
};

window.changeLanguage = function(lang) {
    if (lang !== 'zh' && lang !== 'en') lang = 'zh';
    localStorage.setItem('vmap_set_lang', lang);
    window.updateUIForLanguage();
};

window.updateUIForLanguage = function() {
    const currentLang = localStorage.getItem('vmap_set_lang') || 'zh';
    const dict = LANG_DICTIONARY[currentLang];
    if (!dict) return;
    
    // Process static selector bindings
    for (const [selector, html] of Object.entries(dict)) {
        const els = document.querySelectorAll(selector);
        els.forEach(el => {
            if (el.tagName === 'INPUT' && (el.type === 'text' || el.type === 'placeholder')) {
                el.placeholder = html;
            } else {
                el.innerHTML = html;
            }
        });
    }
    
    // Sync the dropdown select option if it exists
    const selectEl = document.getElementById('selectLanguage');
    if (selectEl) {
        selectEl.value = currentLang;
    }
    
    // Update document title
    if (currentLang === 'en') {
        document.title = "VocalMap - Professional Acoustic Diagnosis & Stem Separation Station";
    } else {
        document.title = "VocalMap - 专业级声学多维诊断平台";
    }
    
    // Re-render Lucide vector icons
    if (window.lucide) {
        window.lucide.createIcons();
    }
    
    // Dispatch custom event to notify components that language has loaded/switched
    window.dispatchEvent(new CustomEvent('languagechanged', { detail: currentLang }));
};

window.initLanguage = function() {
    const savedLang = localStorage.getItem('vmap_set_lang');
    if (savedLang) {
        window.changeLanguage(savedLang);
    } else {
        // Fallback to browser navigator language preference
        const sysLang = navigator.language || navigator.userLanguage;
        if (sysLang && sysLang.toLowerCase().startsWith('en')) {
            window.changeLanguage('en');
        } else {
            window.changeLanguage('zh');
        }
    }
};

// Auto-run lang initializer when DOM is loaded
window.addEventListener('DOMContentLoaded', () => {
    window.initLanguage();
});
